# Generated by Django 5.0.1 on 2024-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobileno", models.IntegerField()),
                ("message", models.TextField(max_length=200)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
