# Generated by Django 5.0.1 on 2024-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_formdata_mobileno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdata",
            name="message",
            field=models.TextField(max_length=400),
        ),
    ]
